spring:
  servlet:
    multipart:
    # Increase these if need to upload bigger jars
      max-file-size: 10MB
      max-request-size: 10MB

# Parameters for configuring Cassandra connection
cassandra:
  host: 127.0.0.1
  port: 9042
  keyspace: dispersibility

# Parameters for running the jar to create a service on Gigapaxos
create-service:
  jar-path: create-service-jar/create-service.jar
  properties-path: create-service-jar/dispersible.properties
  keystore-pass: qwerty
  keystore-path: /home/sarthak/IdeaProjects/gigapaxos-s7/conf/keyStore.jks
  truststore-pass: qwerty
  truststore-path: /home/sarthak/IdeaProjects/gigapaxos-s7/conf/trustStore.jks
  logging-config: /home/sarthak/IdeaProjects/gigapaxos-s7/conf/logging.properties
  log4j-config: /home/sarthak/IdeaProjects/gigapaxos-s7/conf/log4j.properties